title: "Yechan Park"
description: "Predoctoral Research Fellow at Opportunity Insights, Harvard University"
email: "yechanpark@fas.harvard.edu"
theme: minima
header_pages:
  - index.md
  - research.md
  - cv.md
sass:
  style: compressed
